# risk model (initialized explicitly in interventions.utils.get_intervention_conf)
RISK_MODEL : "heuristic"
HEURISTIC_VERSION: 2

# behavior specifications
SHOULD_MODIFY_BEHAVIOR : True

# sequence
INTERVENTION_TRIGGER: "DAYS_SINCE_OUTBREAK"
INTERVENTION_SEQUENCE: [
  [ 0, "HEURISTIC" ]
]
