# name of this configuration file
INTERVENTION_NAME: "heuristicv3_wo_hhld"

# risk model
RISK_MODEL : "heuristicv3"

# behavior level specifications
N_BEHAVIOR_LEVELS: 4
SHOULD_MODIFY_BEHAVIOR : True

# tracing parameters (not used in heuristic)
TRACING_ORDER : 1

# household members
MAKE_HOUSEHOLD_BEHAVE_SAME_AS_MAX_RISK_RESIDENT: False

# behavior modification (not used in heuristic)
REC_LEVEL_THRESHOLDS: []

# when to start (overwrite it if needs to be run from other day)
INTERVENTION_DAY: 0
