# risk model
RISK_MODEL : "transformer"
USE_ORACLE: True

# behavior level specifications
N_BEHAVIOR_LEVELS: 4
INTERPOLATE_CONTACTS_USING_LOCKDOWN_CONTACTS: True
SHOULD_MODIFY_BEHAVIOR : True

# tracing parameters (not used in oracle)
TRACING_ORDER : 1

# behavior modification
REC_LEVEL_THRESHOLDS: [1, 3, 5]
MAX_RISK_LEVEL: 15

# when to start (overwrite it if needs to be run from other day)
INTERVENTION_DAY: 0

# EXPERIMENTAL PARAMETERS
COLLECT_LOGS: False
COLLECT_TRAINING_DATA: False
USE_INFERENCE_SERVER: False
ORACLE_NOISE: 0.0

## INTERVENTIONS
INTERVENTION: "Tracing"

# TWILIGHT-RAIN-696 (not used in oracle)
TRANSFORMER_EXP_PATH: "https://drive.google.com/file/d/1kXA-0juviQOL0R08YlQpaS5gKumQ8zrT"
CLUSTER_PATH: "output/clusters"

RISK_MAPPING:
  [
    0.0,
    0.010190361,
    0.022800818,
    0.033924844,
    0.044960417,
    0.0564146,
    0.069076724,
    0.08331901,
    0.09839013,
    0.115344636,
    0.13295256,
    0.15386948,
    0.1748018,
    0.19909734,
    0.22582635,
    0.26276696,
    1.0,
  ]
