RISK_MODEL : "digital"
SHOULD_MODIFY_BEHAVIOR : True

## INTERVENTIONS
INTERVENTION : "Tracing"
N_BEHAVIOR_LEVELS: 4

# TRACING RISK MODEL PARAMETERS  (non-ML)
TRACING_ORDER : 1
REC_LEVEL_THRESHOLDS: [0, 0, 1] # Binary
