RISK_MODEL: ""
N_BEHAVIOR_LEVELS: 2
INTERPOLATE_CONTACTS_USING_LOCKDOWN_CONTACTS: False
SHOULD_MODIFY_BEHAVIOR: True
INTERVENTION_DAY: -1
QUARANTINE_HOUSEHOLD_UPON_INDIVIDUAL_POSITIVE_TEST: False
ASSUME_SAFE_HOSPITAL_DAILY_INTERACTIONS: False
