# simulation parameters
n_people: 1000
init_fraction_sick: 0.001
seed: 0
simulation_days: 30
start_time: "2020-02-28 00:00:00"  # parsed into a datetime object with the following schema: '%Y-%m-%d %H:%M:%S'

# (output) to store final output
outdir: ./output
out_chunk_size: null

# (data collection and loggin)
tune: False
zip_outdir: False
delete_outdir: False
COLLECT_LOGS: False
COLLECT_TRAINING_DATA: False
USE_INFERENCE_SERVER: False
INFERENCE_SERVER_ADDRESS: null

# (tracing) default parameters
# NOTE: HAS_APP params are only used when an app based INTERVENTION = "Tracing" is used
APP_UPTAKE: -1.0
TRACING_N_DAYS_HISTORY: 14
UPDATES_PER_DAY: 4

# (risk mapping) by default, we use a roughly linear interpolation to map the risk values
RISK_MAPPING:
  [
    0.0,
    0.04375,
    0.0875,
    0.13124999999999998,
    0.175,
    0.21875,
    0.26249999999999996,
    0.30624999999999997,
    0.35,
    0.39375,
    0.4375,
    0.48124999999999996,
    0.5249999999999999,
    0.56875,
    0.6124999999999999,
    0.65625,
    0.7
  ]
MAX_RISK_LEVEL: 15 # maximum allowed risk_level => assert risk_level in range(0, MAX_RISK_LEVEL + 1)


# clustering related parameters
DUMP_CLUSTERS: False
CLUSTER_ALGO_TYPE: "blind" # should be in ["old", "blind", "naive", "perfect", "simple"]
